# config.toml
base_url = "/website/public"
title = "Brilliant Focus"
description = ""
compile_sass = true
build_search_index = false

[markdown]
highlight_code = true


[extra]
author = "Brilliant Focus"
